---
version: 0.2

env:
  variables:
    K8S_DEPLOYMENT_APP: "cantaloupe"
    K8S_NAMESPACE: "test-iiif"
    K8S_DEPLOYMENT_CONTAINER_IMAGE_TAG: "latest"
phases:
  install:
    commands:
      - apk add --update curl py-pip jq
      - pip install awscli
  build:
    commands:
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - export PATH=$PWD/:$PATH
      - aws --version
      - aws eks update-kubeconfig --name test-iiif-cluster --region us-west-2 --role-arn arn:aws:iam::053298376377:role/ucla-terraform_iiif-k8s-deployment-robot
      - terraform version
      - |
          TF_ENV_SUBPATH=$(echo "${K8S_NAMESPACE}" | cut -d '-' -f1)
          cd environments/$TF_ENV_SUBPATH/k8s && terraform init
          terraform apply --auto-approve -var-file=$TF_ENV_SUBPATH.tfvars -var "${K8S_DEPLOYMENT_APP}_deployment_container_image_version=${K8S_DEPLOYMENT_CONTAINER_IMAGE_TAG}"
          if [ "${K8S_DEPLOYMENT_CONTAINER_IMAGE_TAG}" = "latest" ] ; then
            kubectl -n $K8S_NAMESPACE rollout restart deployment/$K8S_DEPLOYMENT_APP
          fi
