version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo test
build:
    commands:
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - kubectl -v
      - export PATH=$PWD/:$PATH
#      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
#      - kubectl -n $NAMESPACE get deployments
