version: 0.2
phases:
  install:
    commands:
      - echo test
      - apk add --update curl py-pip jq
      - pip install awscli
  build:
    commands:
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - export PATH=$PWD/:$PATH
      - aws --version
      - aws sts get-caller-identity
      - aws eks update-kubeconfig --name test-iiif-cluster --region us-west-2 --role-arn arn:aws:iam::053298376377:role/ucla-terraform_iiif-k8s-deployment-robot
      - terraform version
      - pwd
      - ls -la
      - kubectl version
      - kubectl get deployments -n test-iiif
      - kubectl -n test-iiif rollout restart deployment/cantaloupe-deployment
      - kubectl -n test-iiif rollout status deployment/cantaloupe-deployment
#      - kubectl -n $NAMESPACE get deployments
