version: 0.2
phases:
  install:
    commands:
      - echo test
      - apk add --update curl py-pip
      - pip install awscli
  build:
    commands:
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - export PATH=$PWD/:$PATH
      - kubectl version
#      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
#      - kubectl -n $NAMESPACE get deployments
