apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "test-iiif-ingress"
  namespace: "test-iiif"
  annotations:
    nginx.ingress.kubernetes.io/default-backend: cantaloupe-service
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
#    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/default-backend: cantaloupe-service
spec:
  rules:
  - http:
      paths:
        - path: /fester/.*
          backend:
            serviceName: fester-service
            servicePort: 8183
        - path: /collections
          backend:
            serviceName: fester-service
            servicePort: 8183
        - path: /collections/.*
          backend:
            serviceName: fester-service
            servicePort: 8183
        - path: /status/fester
          backend:
            serviceName: fester-service
            servicePort: 8183
        - path: /.*/manifest
          backend:
            serviceName: fester-service
            servicePort: 8183
        - path:
          backend:
            serviceName: cantaloupe-service
            servicePort: 8182
